apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2048
  name: app-2048
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-2048
  type: LoadBalancer
  
